---
swagger: 2.0
basePath: /Prod
info:
  title: GenericSdkExampleApi
schemes:
- https
paths:
  /sdk-example/{proxy+}:
    x-amazon-apigateway-any-method:
      produces:
      - application/json
      x-amazon-apigateway-integration:
        responses:
          default:
            statusCode: 200
        uri: arn:aws:apigateway:us-west-2:lambda:path/2015-03-31/functions/arn:aws:lambda:us-west-2:975344022805:function:SdkExample/invocations
        httpMethod: POST
        type: aws_proxy
  /hello:
    get:
      x-amazon-apigateway-auth:
        type: aws_iam
      produces:
      - application/json
      x-amazon-apigateway-integration:
        uri: arn:aws:apigateway:us-west-2:lambda:path/2015-03-31/functions/arn:aws:lambda:us-west-2:975344022805:function:SdkExampleHelloIAM/invocations
        httpMethod: POST
        type: aws_proxy
